kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    labels:
      learning.jeevanm84/worker: "a"
  - role: worker
    labels:
      learning.jeevanm84/worker: "b"
